name: Test

on:
  push:
    tags:
      - "*"
    branches-ignore:
      - 'exp_*'
  pull_request:
    branches-ignore:
      - 'exp_*'

jobs:
  test:
    name: Test ImageMagick7
    runs-on: ubuntu-latest
    environment: imagemagick7
    env:
      DOCKER_IMAGE: gographics/imagick.v3:im-${{ vars.IMAGEMAGICK7_VERSION }}
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          docker run --rm \
            -v $PWD:/go/projects/imagick \
            -v $PWD/.cache/go-build:/root/.cache/go-build \
            -v $PWD/.cache/go/pkg:/go/pkg \
            "$DOCKER_IMAGE"
